In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Top-Películas.csv')
df

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
...,...,...,...,...,...,...,...,...,...,...
2527,2527,998.0,The Invisible Man,James Whale,1933.0,71.0,Terror,7.6,87.0,0.00
2528,2528,998.0,The Invisible Man,James Whale,1933.0,71.0,Ciencia Ficción,7.6,87.0,0.00
2529,2529,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Acción,7.6,0.0,0.00
2530,2530,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Crimen,7.6,0.0,0.00
2531,2531,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Drama,7.6,0.0,0.00

In [9]:
#Ordenar datos del df, en este caso específico por rating
df_ordenado = df.sort_values(by = 'rating')#Lo va a ordenar de menor a mayor gracias a la fn sort...
df_ordenado.head(40)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
2531,2531,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Drama,7.6,0.0,0.00
2530,2530,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Crimen,7.6,0.0,0.00
2529,2529,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Acción,7.6,0.0,0.00
2528,2528,998.0,The Invisible Man,James Whale,1933.0,71.0,Ciencia Ficción,7.6,87.0,0.00
2495,2495,986.0,From Here to Eternity,Fred Zinnemann,1953.0,118.0,Guerra,7.6,85.0,30.50
2496,2496,987.0,50/50,Jonathan Levine,2011.0,100.0,Comedia,7.6,72.0,35.01
2497,2497,987.0,50/50,Jonathan Levine,2011.0,100.0,Drama,7.6,72.0,35.01
2482,2482,981.0,After Hours,Martin Scorsese,1985.0,97.0,Drama,7.6,90.0,10.60
2483,2483,982.0,Sabrina,Billy Wilder,1954.0,113.0,Comedia,7.6,72.0,0.00
2484,2484,982.0,Sabrina,Billy Wilder,1954.0,113.0,Drama,7.6,72.0,0.00
2485,2485,982.0,Sabrina,Billy Wilder,1954.0,113.0,Romance,7.6,72.0,0.00
2486,2486,983.0,Die Hard with a Vengeance,John McTiernan,1995.0,128.0,Acción,7.6,58.0,100.01
2487,2487,983.0,Die Hard with a Vengeance,John McTiernan,1995.0,128.0,Aventura,7.6,58.0,100.01
2488,2488,983.0,Die Hard with a Vengeance,John McTiernan,1995.0,128.0,Thriller,7.6,58.0,100.01
2489,2489,984.0,Rebel Without a Cause,Nicholas Ray,1955.0,111.0,Drama,7.6,89.0,0.00
2490,2490,985.0,Snow White and the Seven Dwarfs,William Cottrell,1937.0,83.0,Animación,7.6,96.0,184.93
2491,2491,985.0,Snow White and the Seven Dwarfs,William Cottrell,1937.0,83.0,Aventura,7.6,96.0,184.93
2492,2492,985.0,Snow White and the Seven Dwarfs,William Cottrell,1937.0,83.0,Familiar,7.6,96.0,184.93
2493,2493,986.0,From Here to Eternity,Fred Zinnemann,1953.0,118.0,Drama,7.6,85.0,30.50
2494,2494,986.0,From Here to Eternity,Fred Zinnemann,1953.0,118.0,Romance,7.6,85.0,30.50
2463,2463,974.0,Enter the Dragon,Robert Clouse,1973.0,102.0,Crimen,7.6,83.0,25.00
2464,2464,974.0,Enter the Dragon,Robert Clouse,1973.0,102.0,Thriller,7.6,83.0,25.00
2465,2465,975.0,End of Watch,David Ayer,2012.0,109.0,Acción,7.6,68.0,41.00
2466,2466,975.0,End of Watch,David Ayer,2012.0,109.0,Aventura,7.6,68.0,41.00
2467,2467,975.0,End of Watch,David Ayer,2012.0,109.0,Crimen,7.6,68.0,41.00
2468,2468,976.0,Dark Waters,Todd Haynes,2019.0,126.0,Biografía,7.6,73.0,0.00
2469,2469,976.0,Dark Waters,Todd Haynes,2019.0,126.0,Drama,7.6,73.0,0.00
2470,2470,976.0,Dark Waters,Todd Haynes,2019.0,126.0,Historia,7.6,73.0,0.00
2471,2471,977.0,Dawn of the Planet of the Apes,Matt Reeves,2014.0,130.0,Acción,7.6,79.0,208.55
2472,2472,977.0,Dawn of the Planet of the Apes,Matt Reeves,2014.0,130.0,Aventura,7.6,79.0,208.55
2473,2473,977.0,Dawn of the Planet of the Apes,Matt Reeves,2014.0,130.0,Drama,7.6,79.0,208.55
2474,2474,978.0,I Am Sam,Jessie Nelson,2001.0,132.0,Drama,7.6,28.0,40.31
2475,2475,979.0,Match Point,Woody Allen,2005.0,124.0,Drama,7.6,72.0,23.09
2476,2476,979.0,Match Point,Woody Allen,2005.0,124.0,Romance,7.6,72.0,23.09
2477,2477,979.0,Match Point,Woody Allen,2005.0,124.0,Thriller,7.6,72.0,23.09
2478,2478,980.0,The Bridges of Madison County,Clint Eastwood,1995.0,135.0,Drama,7.6,69.0,71.52
2447,2447,969.0,Dark City,Alex Proyas,1998.0,100.0,Fantasía,7.6,66.0,14.38
2448,2448,969.0,Dark City,Alex Proyas,1998.0,100.0,Misterio,7.6,66.0,14.38
2449,2449,969.0,Dark City,Alex Proyas,1998.0,100.0,Ciencia Ficción,7.6,66.0,14.38
2450,2450,970.0,Gone Baby Gone,Ben Affleck,2007.0,114.0,Crimen,7.6,72.0,20.30

In [13]:
#Ordenado del df pero ahora de mayor a menor...
df_ordenado = df.sort_values('rating',ascending=False)#Esto de ordenar al revez lo logramos pq desactivamos el ascending y le metimos False
df_ordenado

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
5,5,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Drama,9.0,84.0,534.86
12,12,5.0,The Lord of the Rings: The Return of the King,Peter Jackson,2003.0,201.0,Aventura,9.0,94.0,377.85
...,...,...,...,...,...,...,...,...,...,...
2048,"2048,810,""O Brother, Where Art Thou?"",Joel Coe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2049,"2049,810,""O Brother, Where Art Thou?"",Joel Coe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2138,"2138,847,""South Park: Bigger, Longer & Uncut"",...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2139,"2139,847,""South Park: Bigger, Longer & Uncut"",...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,"2140,847,""South Park: Bigger, Longer & Uncut"",...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#Ordenamiento en funcion de varias columnas
df_ordenado = df.sort_values(by=['rating','recaudación(M)'],ascending = False)#Le metemos otra columna colocando el nombre de la misma en la lista
df_ordenado

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
...,...,...,...,...,...,...,...,...,...,...
2048,"2048,810,""O Brother, Where Art Thou?"",Joel Coe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2049,"2049,810,""O Brother, Where Art Thou?"",Joel Coe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2138,"2138,847,""South Park: Bigger, Longer & Uncut"",...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2139,"2139,847,""South Park: Bigger, Longer & Uncut"",...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,"2140,847,""South Park: Bigger, Longer & Uncut"",...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#Agrupación de los géneros de las películas y obtener el promedio de rating de cada uno de esos géneros para el orden
df_agrupado = df.groupby('género')['rating'].mean()#Agrupamos gracias a groupby ahí le ponemos el name del género, dps le decimos que queremos ordenar ese grupo por el rating y aplicarle la fn mean q es para obtener el promedio de rating de cada género
df_agrupado#Impresión para obtener la agrup de los géneros, ordenados por el promedio del rating de cada uno

género
Acción             7.987255
Animación          7.943902
Aventura           7.980435
Biografía          7.971698
Ciencia Ficción    7.986567
Comedia            7.909910
Crimen             7.993500
Deportes           7.980000
Drama              7.980444
Familiar           7.932692
Fantasía           7.929508
Film-Noir          7.977273
Guerra             8.053191
Historia           7.931818
Misterio           7.991262
Musica             7.909677
Musical            7.943750
Romance            7.937398
Terror             7.875758
Thriller           7.929286
Western            8.006250
Name: rating, dtype: float64

In [29]:
#Agrupacion de las películas por el año y ordenar los años por la recaudación de cada uno
df_agrupado = df.groupby('año')['recaudación(M)'].sum()#Agrupamos por año y ordenamos por la recaudación total(suma) de cada año  
df_agrupado.sort_values(ascending = False).head(10)#Aplicamos la fn sort... para ordenar esto de mayor a menor y que nos muestre los 10 1eros

año
2014.0    8015.90
2019.0    7092.95
2010.0    6899.96
2016.0    6860.23
2015.0    6817.12
2012.0    6487.22
2009.0    6486.34
2018.0    5992.02
2008.0    5603.30
2017.0    5381.90
Name: recaudación(M), dtype: float64