In [1]:
import pandas as pd
import numpy as np

Obtener y limpiar los datos

    Te puedo pasar un dataset de ventas en formato CSV o podés generar uno aleatorio.
    Usa Pandas para cargar el dataset y revisar datos faltantes.
    Elimina valores nulos y transforma formatos de fecha y precios.

In [2]:
df = pd.read_csv('datos_ventas.csv')
df

,Fecha,Producto,Categoría,Cantidad,Precio Unitario,Total Venta
0,2024-04-12,Smartphone,Accesorios,2,800,1600
1,2025-03-11,Mouse,Accesorios,1,50,50
2,2024-12-14,Tablet,Computación,3,500,1500
3,2024-09-27,Smartphone,Electrónica,6,800,4800
4,2024-04-16,Smartphone,Electrónica,8,800,6400
...,...,...,...,...,...,...
495,2024-04-23,Monitor,Accesorios,9,300,2700
496,2024-10-14,Mouse,Accesorios,1,50,50
497,2025-03-06,Laptop,Computación,6,1200,7200
498,2024-12-07,Smartphone,Accesorios,9,800,7200
499,2024-05-30,Smartphone,Computación,8,800,6400

In [4]:
pd.isna(df).sum()

Fecha              0
Producto           0
Categoría          0
Cantidad           0
Precio Unitario    0
Total Venta        0
dtype: int64

In [8]:
type(df['Fecha'][0])

str

In [9]:
type(df['Precio Unitario'][0])

numpy.int64

In [12]:
df['Fecha'] = pd.to_datetime(df['Fecha'])
type(df['Fecha'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [20]:
df['Precio Unitario'] = df['Precio Unitario'].astype(float)
type(df['Precio Unitario'][0])

numpy.float64

Análisis exploratorio con Pandas

    Filtra los datos por mes, categoría de producto o cliente.
    Agrupa por categoría o por mes para calcular ingresos totales.
    Identifica los productos más vendidos.

In [29]:
#Flitracion de ventas por el mes de Julio
df['Mes'] = df['Fecha'].dt.month
mes_julio = df[df['Mes'] == 7]
mes_julio

,Fecha,Producto,Categoría,Cantidad,Precio Unitario,Total Venta,Mes
6,2024-07-07,Laptop,Electrónica,7,1200.0,8400,7
28,2024-07-10,Monitor,Electrónica,1,300.0,300,7
43,2024-07-06,Impresora,Accesorios,2,200.0,400,7
46,2024-07-08,Teclado,Electrónica,4,100.0,400,7
81,2024-07-24,Tablet,Electrónica,6,500.0,3000,7
94,2024-07-09,Mouse,Computación,2,50.0,100,7
99,2024-07-20,Smartphone,Electrónica,3,800.0,2400,7
110,2024-07-08,Smartphone,Accesorios,4,800.0,3200,7
112,2024-07-31,Laptop,Accesorios,8,1200.0,9600,7
113,2024-07-26,Mouse,Electrónica,1,50.0,50,7
122,2024-07-06,Monitor,Computación,2,300.0,600,7
153,2024-07-19,Impresora,Accesorios,7,200.0,1400,7
183,2024-07-25,Impresora,Accesorios,4,200.0,800,7
209,2024-07-05,Impresora,Accesorios,9,200.0,1800,7
231,2024-07-08,Teclado,Electrónica,7,100.0,700,7
243,2024-07-16,Impresora,Electrónica,2,200.0,400,7
276,2024-07-05,Laptop,Accesorios,9,1200.0,10800,7
294,2024-07-16,Auriculares,Accesorios,8,150.0,1200,7
299,2024-07-21,Mouse,Computación,7,50.0,350,7
300,2024-07-02,Impresora,Electrónica,8,200.0,1600,7
309,2024-07-16,Auriculares,Accesorios,6,150.0,900,7
315,2024-07-19,Monitor,Electrónica,1,300.0,300,7
317,2024-07-05,Impresora,Electrónica,8,200.0,1600,7
332,2024-07-17,Tablet,Computación,8,500.0,4000,7
373,2024-07-26,Auriculares,Computación,8,150.0,1200,7
400,2024-07-12,Laptop,Computación,3,1200.0,3600,7
403,2024-07-26,Auriculares,Accesorios,7,150.0,1050,7
417,2024-07-13,Monitor,Electrónica,1,300.0,300,7
452,2024-07-10,Impresora,Accesorios,3,200.0,600,7
473,2024-07-06,Auriculares,Electrónica,4,150.0,600,7
476,2024-07-09,Teclado,Accesorios,1,100.0,100,7

In [31]:
#Filtramos las ventas donde venden accesorios
ventas_accesorios = df[df['Categoría'] == 'Accesorios']
ventas_accesorios

,Fecha,Producto,Categoría,Cantidad,Precio Unitario,Total Venta,Mes
0,2024-04-12,Smartphone,Accesorios,2,800.0,1600,4
1,2025-03-11,Mouse,Accesorios,1,50.0,50,3
7,2024-01-21,Impresora,Accesorios,4,200.0,800,1
9,2024-05-01,Laptop,Accesorios,5,1200.0,6000,5
14,2024-03-28,Monitor,Accesorios,2,300.0,600,3
...,...,...,...,...,...,...,...
488,2024-08-10,Teclado,Accesorios,8,100.0,800,8
493,2024-06-22,Tablet,Accesorios,2,500.0,1000,6
495,2024-04-23,Monitor,Accesorios,9,300.0,2700,4
496,2024-10-14,Mouse,Accesorios,1,50.0,50,10
498,2024-12-07,Smartphone,Accesorios,9,800.0,7200,12

In [36]:
#Filtramos precios, donde tiene que ser mayor a 100 y menor a 500
precio_300_500 = df[(df['Precio Unitario']>100) & (df['Precio Unitario']<500)]
precio_300_500

,Fecha,Producto,Categoría,Cantidad,Precio Unitario,Total Venta,Mes
7,2024-01-21,Impresora,Accesorios,4,200.0,800,1
12,2024-11-26,Impresora,Computación,1,200.0,200,11
14,2024-03-28,Monitor,Accesorios,2,300.0,600,3
21,2024-11-04,Impresora,Electrónica,1,200.0,200,11
22,2024-09-14,Monitor,Electrónica,4,300.0,1200,9
...,...,...,...,...,...,...,...
486,2024-10-07,Monitor,Electrónica,2,300.0,600,10
487,2025-05-04,Monitor,Electrónica,8,300.0,2400,5
490,2024-02-27,Monitor,Computación,8,300.0,2400,2
494,2024-10-06,Impresora,Computación,6,200.0,1200,10
495,2024-04-23,Monitor,Accesorios,9,300.0,2700,4

In [38]:
#Agrupamos por categoria y obtenmos el total de cada cat
df.groupby('Categoría')['Total Venta'].sum()

Categoría
Accesorios     326500
Computación    364200
Electrónica    341500
Name: Total Venta, dtype: int64

In [39]:
#Agruo por mes y obtenemos el total de todos los meses
df.groupby('Mes')['Total Venta'].sum()

Mes
1     136800
2      97050
3     102700
4     168600
5     131300
6      58450
7      61750
8      61200
9      54150
10     64650
11     42050
12     53500
Name: Total Venta, dtype: int64

In [42]:
#Top 3 de prod más vendidos
df.groupby('Producto')['Total Venta'].max().head(3)

Producto
Auriculares     1350
Impresora       1800
Laptop         10800
Name: Total Venta, dtype: int64